---
title: 错误和异常
categories: Python语法
date: 2019-02-10 19:42:03
---
&emsp;&emsp;`Python`有两种错误很容易辨认：语法错误和异常。`Python`标准异常总结如下：<!--more-->

异常                    | 说明                  | 异常                    | 说明
------------------------|----------------------|-------------------------|-----
`AssertionError`        | 断言语句失败          | `AttributeError`        | 尝试访问未知的对象属性
`FloatingPointError`    | 浮点计算错误          | `EOFError`              | 用户输入文件末尾标志`EOF`，即`Ctrl + d`
`ImportError`           | 导入模块失败的时候     | `GeneratorExit`         | `generator.close`方法被调用的时候
`IndexError`            | 索引超出序列的范围     | `KeyError`              | 字典中查找一个不存在的关键字
`MemoryError`           | 内存溢出              | `KeyboardInterrupt`     | 用户输入中断键，即`Ctrl + c`
`NotImplementedError`   | 尚未实现的方法         | `NameError`             | 尝试访问一个不存在的变量
`OverflowError`         | 数值运算超出最大限制    | `OSError`               | 操作系统产生的异常，例如打开一个不存在的文件
`RuntimeError`          | 一般的运行时错误        | `ReferenceError`        | 弱引用试图访问一个已经被垃圾回收机制回收了的对象
`StopIteration`         | 迭代器没有更多的值      | `SyntaxError`           | `Python`的语法错误
`IndentationError`      | 缩进错误               | `TabError`              | `Tab`和空格混合使用
`SystemError`           | `Python`编译器系统错误 | `SystemExit`            | `Python`编译器进程被关闭
`TypeError`             | 不同类型间的无效操作    | `UnboundLocalError`     | 访问一个未初始化的本地变量
`UnicodeError`          | `Unicode`相关的错误    | `UnicodeEncodeError`    | `Unicode`编码时的错误
`UnicodeDecodeError`    | `Unicode`解码时的错误  | `UnicodeTranslateError` | `Unicode`转换时的错误
`ValueError`            | 传入无效的参数         | `ZeroDivisionError`     | 除数为零

### 错误

&emsp;&emsp;`Python`的语法错误称之为`解析错误`：

``` python
>>> while True print('Hello world')
SyntaxError: invalid syntax
```

&emsp;&emsp;即便语法是正确的，运行时也有可能发生错误。运行期检测到的错误被称为`异常`：

``` python
>>> 10 * (1 / 0)
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    10 * (1 / 0)
ZeroDivisionError: division by zero
```

### 异常处理

&emsp;&emsp;用户的中断信息会引发一个`KeyboardInterrupt`异常：

``` python
while True:
    try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
        print("Oops! That was no valid number. Try again!")
```

&emsp;&emsp;`try`语句按照如下方式工作：

1. 首先执行`try`子句，即在关键字`try`和`except`之间的语句。
2. 如果没有异常发生，则忽略`except`子句，`try`子句执行后结束。
3. 如果在执行`try`子句的过程中发生了异常，那么`try`子句余下的部分将被忽略。
4. 如果异常的类型和`except`之后的名称相符，那么对应的`except`子句将被执行。
5. 最后执行`try`语句之后的代码。
6. 如果一个异常没有与任何的`except`匹配，那么这个异常将会传递给上层的`try`中。

&emsp;&emsp;一个`try`语句可能包含多个`except`子句，分别来处理不同的特定的异常，最多只有一个分支会被执行。
&emsp;&emsp;一个`except`子句可以同时处理多个异常，这些异常将被放在一个括号里成为一个元组：

``` python
except (RuntimeError, TypeError, NameError):
    pass
```

&emsp;&emsp;最后一个`except`子句可以忽略异常的名称，它将被当作通配符使用：

``` python
import sys

try:
    f = open('myfile.txt')
    s = f.readline()
    i = int(s.strip())
except OSError as err:
    print("OS error: {0}".format(err))
except ValueError:
    print("Could not convert data to an integer.")
except:
    print("Unexpected error:", sys.exc_info()[0])
    raise
```

&emsp;&emsp;`try`语句还有一个可选的`else`子句，这个子句将在`try`没有发生任何异常的时候执行：

``` python
import sys

for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except IOError:
        print('cannot open', arg)
    else:
        print(arg, 'has', len(f.readlines()), 'lines')
        f.close()
```

&emsp;&emsp;异常处理并不仅仅处理那些直接发生在`try`子句中的异常，而且还能处理子句中调用的函数里抛出的异常：

``` python
def this_fails():
    x = 1 / 0

try:
    this_fails()
except ZeroDivisionError as err:
    print('Handling run-time error:', err)
```

上述代码抛出如下异常：

``` python
Handling run-time error: int division or modulo by zero
```

### 抛出异常

&emsp;&emsp;使用`raise`语句抛出一个指定的异常：

``` python
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
```

### 自定义异常

&emsp;&emsp;用户可以自定义一个异常，该异常应该继承自`Exception`类：

``` python
class MyError(Exception):
    def __init__(self, value):
        self.value = value

    def __str__(self):
        return repr(self.value)

try:
    raise MyError(2 * 2)
except MyError as e:
    print('My exception occurred, value:', e.value)
```

执行结果：

``` python
My exception occurred, value: 4
```

### finally子句

&emsp;&emsp;`try`语句还有一个可选的`finally`子句，它定义了无论在任何情况下都会执行的清理行为：

``` python
try:
    raise KeyboardInterrupt
finally:
    print('Goodbye, world!')
```

执行结果：

``` python
Goodbye, world!
Traceback (most recent call last):
  File "test_python.py", line 2, in <module>
    raise KeyboardInterrupt
KeyboardInterrupt
```

以上示例不管`try`子句里面有没有发生异常，`finally`子句都会执行。

### assert

&emsp;&emsp;`Python`的`assert`断言是声明表达式的值必须为`True`的判定。如果发生异常，就说明该表达式为`False`：

``` python
assert len(lists) >= 5, '列表元素个数小于5'
assert 2 == 1, '2不等于1'
```